# Generated by Django 3.2.11 on 2022-04-12 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20220412_0733'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usertradingaccount',
            old_name='total_balance',
            new_name='total_deposit',
        ),
        migrations.AddField(
            model_name='usertradingaccount',
            name='total_profit',
            field=models.CharField(default='0', max_length=255),
        ),
    ]
