# Generated by Django 3.2.11 on 2022-04-12 20:29

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20220412_0748'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accountverification',
            old_name='image',
            new_name='id_image',
        ),
        migrations.AddField(
            model_name='accountverification',
            name='profile_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
