# Generated by Django 3.2.11 on 2022-04-12 20:43

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20220412_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountverification',
            name='id_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='ID image'),
        ),
        migrations.AlterField(
            model_name='accountverification',
            name='profile_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Profile image'),
        ),
    ]
