# Generated by Django 3.2.11 on 2022-05-03 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20220412_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='investment_plan',
            field=models.CharField(choices=[('STARTER PLAN', 'STARTER PLAN'), ('PREMIUM PLAN', 'PREMIUM PLAN'), ('SPECIAL PLAN', 'SPECIAL PLAN'), ('VIP PLAN', 'VIP PLAN'), ('DEBUT PLAN', 'DEBUT PLAN')], default='CLASSIC', max_length=255),
        ),
    ]
