# Generated by Django 3.2.11 on 2022-05-05 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_investment_investment_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='cryptocurrency',
            field=models.CharField(choices=[('BITCOIN', 'BITCOIN'), ('ETHEREUM', 'ETHEREUM'), ('TETHER', 'TETHER')], default='Bitcoin', max_length=255),
        ),
    ]
