# Generated by Django 3.2.11 on 2022-05-05 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, unique=True)),
                ('email', models.TextField(max_length=70)),
                ('Subject', models.TextField(max_length=50)),
                ('message', models.TextField(max_length=300)),
            ],
        ),
    ]
